site_name: snackCheck
theme:
  name: material
  icon:
    logo: material/candy
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: pink
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: pink
      accent: indigo
  font:
    text: Montserrat
    code: Roboto Mono

nav:
  - Home: index.md
  - Account:
      - /register: Account/register.md
      - /accounts: Account/accounts.md
      - /login: Account/login.md
      - /password: Account/password.md
      - /token: Account/token.md
      - /logout: Account/logout.md

  - Profile:
      - /photo: Profile/photo.md
      - /fullname: Profile/fullname.md
      - /profile: Profile/profile.md
  - Snack:
      - /predicts: Snack/predicts.md
      - /histories: Snack/histories.md
